services:
  postgres:
    container_name: "snaily-cad-postgres"
    image: postgres:latest
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - cad_web
    volumes:
      - cad_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: "snaily-cad-api"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    expose:
      - ${PORT_API}
    depends_on:
      - postgres
    networks:
      - cad_web
    restart: always
    volumes:
      - ./apps/api/public:/snailycad/apps/api/public

  client:
    container_name: "snaily-cad-client"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    # Optional: If deploying outside of Coolify or a managed router (like Traefik),
    # uncomment the 'ports:' section below to map a host port to the container port.
    # ports:
    #   - "${PORT_CLIENT}:${PORT_CLIENT}"
    expose:
      - ${PORT_CLIENT}
    depends_on:
      - postgres
    networks:
      - cad_web
    restart: always

networks:
  cad_web:

volumes:
  cad_data:
